name: CI

on:
  push: ~
  pull_request: ~
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x]
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: npm ci || npm ci # retry once, install on windows is flaky...
    - name: Build & lint & test
      run: npm run all