name: mutation testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
      
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Run Stryker
        run: npx lerna run --scope "@stryker-mutator/core" --concurrency 1 --stream stryker -- --concurrency 3
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  dependencies_and_plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Run Stryker
        run: npx lerna run --scope "@stryker-mutator/{api,instrumenter,util,jest-runner,karma-runner,mocha-runner,jasmine-runner,cucumber-runner}" --concurrency 1 --stream stryker -- --concurrency 3
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  typescript-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install & Build
        run: |
          npm install
          npm run build
      - name: Run Stryker
        run: npx lerna run --scope "@stryker-mutator/typescript-checker" --concurrency 1 --stream stryker -- --concurrency 2
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  incremental_mutation_test:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Download incremental reports
      run: npm run download-incremental-reports
      env:
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    - name: Run stryker run --incremental
      run: npm run test:mutation:incremental
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
    steps:
    # https://github.com/ryanclark/karma-webpack/issues/494
    - name: Windows temp dir fix
      run: |
        echo TEMP="D:\Temp" >> $env:GITHUB_ENV
        echo TMP="D:\Temp" >> $env:GITHUB_ENV
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: lts/*
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - name: Install dependencies
      run: npm ci || npm ci # retry once, install on windows is flaky...
    - name: Build packages
      run: npm run build
    - name: e2e install
      run: 'npm run e2e:install'
    - name: e2e lint
      run: 'npm run e2e:lint'
    - name: Run e2e tests
      run: 'npm run e2e:run'
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: e2e-reports
        path: |
          e2e/test/*/reports/mutation/
          e2e/test/*/stryker.log